// <auto-generated />
namespace eFlorist.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class databaseclearance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(databaseclearance));
        
        string IMigrationMetadata.Id
        {
            get { return "201801151956006_database-clearance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
